In [39]:
import pandas as pd
import numpy as np

In [40]:
google_df = pd.read_csv("googleplaystore.csv")
apple_df = pd.read_csv("AppleStore.csv")

In [41]:
google_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [42]:
google_df.shape

(10841, 13)

In [43]:
# Checking data types
google_df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [44]:
google_df['Installs'] = google_df['Installs'].str.replace('+','',regex=False)
google_df['Installs'] = google_df['Installs'].str.replace(',','',regex=False)

In [45]:
google_df['Installs'] = pd.to_numeric(google_df['Installs'], errors='coerce')

In [46]:
google_df['Installs'] = google_df['Installs'].fillna(0).astype(int)

In [47]:
google_df.loc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                              3.0M
Size                                               1,000+
Installs                                                0
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [48]:
google_df = google_df.drop(10472)

In [49]:
google_df['Reviews'] = pd.to_numeric(google_df['Reviews'])

In [50]:
google_df['Reviews'] = google_df['Reviews'].astype(int)

In [51]:
google_df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [52]:
google_df['Size'] = google_df['Size'].str.replace('M','')
google_df['Size'] = google_df['Size'].str.replace('K','')

In [53]:
google_df['Size'] = google_df['Size'].replace('Varies with device',None)

In [54]:
google_df['Size'] = pd.to_numeric(google_df['Size'],errors = 'coerce')

In [55]:
google_df['Price'] = google_df['Price'].str.replace('$','', regex=False)

In [56]:
google_df['Price'] = google_df['Price'].astype(float)

In [57]:
google_df['Last Updated'] = pd.to_datetime(google_df['Last Updated'])

In [58]:
google_df['Rating'] = pd.to_numeric(google_df['Rating'], errors='coerce')

In [59]:
google_df.dtypes

App                       object
Category                  object
Rating                   float64
Reviews                    int64
Size                     float64
Installs                   int64
Type                      object
Price                    float64
Content Rating            object
Genres                    object
Last Updated      datetime64[ns]
Current Ver               object
Android Ver               object
dtype: object

In [60]:
google_df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size              2011
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [61]:
google_df['Rating'].median()

4.3

In [62]:
google_df['Rating'] = google_df['Rating'].fillna(google_df['Rating'].median())

In [63]:
google_df['Type'] = google_df['Type'].fillna(google_df['Type'].mode()[0])

In [64]:
google_df['Current Ver'] = google_df['Current Ver'].fillna(google_df['Current Ver'].mode()[0])

In [65]:
google_df['Android Ver'] = google_df['Android Ver'].fillna(google_df['Android Ver'].mode()[0])

In [66]:
google_df['Size'] = google_df['Size'].fillna(google_df['Size'].median())

In [67]:
google_df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [68]:
google_df['Category'].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
Name: count, dtype: int64

In [69]:
google_df['Rating'].value_counts().sort_index()

Rating
1.0      16
1.2       1
1.4       3
1.5       3
1.6       4
1.7       8
1.8       8
1.9      13
2.0      12
2.1       8
2.2      14
2.3      20
2.4      19
2.5      21
2.6      25
2.7      25
2.8      42
2.9      45
3.0      83
3.1      69
3.2      64
3.3     102
3.4     128
3.5     163
3.6     174
3.7     239
3.8     303
3.9     386
4.0     568
4.1     708
4.2     952
4.3    2550
4.4    1109
4.5    1038
4.6     823
4.7     499
4.8     234
4.9      87
5.0     274
Name: count, dtype: int64

In [70]:
google_df['Installs'].value_counts()

Installs
1000000       1579
10000000      1252
100000        1169
10000         1054
1000           907
5000000        752
100            719
500000         539
50000          479
5000           477
100000000      409
10             386
500            330
50000000       289
50             205
5               82
500000000       72
1               67
1000000000      58
0               15
Name: count, dtype: int64

In [73]:
google_df['Reviews'].value_counts()

Reviews
0         596
1         272
2         214
3         175
4         137
         ...
4272        1
5517        1
4057        1
459797      1
398307      1
Name: count, Length: 6001, dtype: int64

In [74]:
google_df['Reviews'].describe()

count    1.084000e+04
mean     4.441529e+05
std      2.927761e+06
min      0.000000e+00
25%      3.800000e+01
50%      2.094000e+03
75%      5.477550e+04
max      7.815831e+07
Name: Reviews, dtype: float64

In [76]:
google_df[['App','Reviews']].sort_values(by='Reviews', ascending=False).head(10)

                                           App   Reviews
2544                                  Facebook  78158306
3943                                  Facebook  78128208
381                         WhatsApp Messenger  69119316
336                         WhatsApp Messenger  69119316
3904                        WhatsApp Messenger  69109672
2604                                 Instagram  66577446
2611                                 Instagram  66577313
2545                                 Instagram  66577313
3909                                 Instagram  66509917
382   Messenger – Text and Video Chat for Free  56646578

In [87]:
bins = [0,1000,10000,100000,1000000,10000000,100000000]
google_df['Review_Group'] = pd.cut(google_df['Reviews'], bins=bins)
google_df['Review_Group'].value_counts()

C:\Users\NarenViji\AppData\Local\Temp\ipykernel_6660\180999755.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  google_df['Review_Group'] = pd.cut(google_df['Reviews'], bins=bins)

Review_Group
(0, 1000]                4145
(10000, 100000]          1964
(1000, 10000]            1529
(100000, 1000000]        1376
(1000000, 10000000]       576
(10000000, 100000000]      87
Name: count, dtype: int64

In [78]:
def is_english(app_name):
    for char in app_name:
        if ord(char) > 127:
            return False
    return True

In [79]:
google_df['App'].apply(is_english)

0         True
1         True
2        False
3         True
4         True
         ...
10836     True
10837     True
10838     True
10839     True
10840     True
Name: App, Length: 10840, dtype: bool

In [81]:
google_df = google_df[google_df['App'].apply(is_english)]

In [83]:
google_df.shape

(10244, 14)

In [84]:
google_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Review_Group
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,"(0, 1000]"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,"(0, 1000]"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,"(100000, 1000000]"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,"(0, 1000]"
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6,50000,Free,0.0,Everyone,Art & Design,2017-03-26,1.0,2.3 and up,"(0, 1000]"

In [88]:
google_df.duplicated().sum()

np.int64(464)

In [90]:
google_df['App'].duplicated().sum()

np.int64(1127)

In [92]:
google_df.groupby('App')['Reviews']

In [93]:
google_df.groupby('App')['Reviews'].idxmax()

App
+Download 4 Instagram Twitter                    8532
- Free Comics - Comic Apps                        324
.R                                               4541
/u/app                                           4636
058.ba                                           5940
                                                 ...
weight conversion calculator                     3312
wetter.com - Weather and Radar                   3652
wikiHow: how to do anything                      8644
yHomework - Math Solver                          4811
zulily - Shop Daily Deals in Fashion and Home    2758
Name: Reviews, Length: 9117, dtype: int64

In [94]:
google_df.shape

(10244, 14)

In [95]:
google_df = google_df.loc[google_df.groupby('App')['Reviews'].idxmax()]

In [96]:
google_df.shape

(9117, 14)

In [97]:
google_df.duplicated().sum()

np.int64(0)